services:
  db:
    image: postgres:17.4
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7.4.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache_data:/data

  web:
    build: .
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - venv:/app/.venv

volumes:
  cache_data:
  db_data:
  venv:
