services:
  db:
    image: postgres:17.4
    env_file: ./.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    env_file: ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - venv:/app/.venv

volumes:
  db_data:
  venv:
